name: This is the name
on:
 push:
    branches:
        - main
 pull_request: 
    branches:
        -  main
 workflow_dispatch: 

jobs:
 hello:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v4
     - name: hello world 
       run: echo "Hello world"
       shell: bash 
 goofbye:
    runs-on: ubuntu-latest
    steps:
     - name: goodbye world 
       run: echo "Good World"
       shell: bash 

 

